name: learn github actions
on: [push, pull_request]
env:
  SERVER: development
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "a code has been pushed"
      - run: echo "this step should only run on main branch"
    if:
      ${{ github.ref == 'refs/heads/master' }}
  hello-feature-branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "pushing on feature branch"
      - run: echo "this step should only run on feature/branch"
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_BASE_REF
      - run: echo $SERVER
    if:
      ${{ github.ref == 'refs/heads/feature/branch' }}
