name: learn github actions
on: [push]
env:
  SERVER: development
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "a code has been pushed"
      - run: echo "this step should only run on main branch"
    if:
      ${{ github.ref == 'refs/heads/master' }}
  hello-go:
    runs-on: ubuntu-latest
    container: golang
    steps:
      - name: go version
      - run: go version
      - name: Checkout repository
      - uses: actions/checkout@v2.3.4
      - name: running the program
      - run: cd cmd
      - run: go run main

  hello-feature-branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "pushing on feature branch"
      - run: echo "this step should only run on feature/branch"
      - run: echo $GITHUB_REF
      - run: echo $SERVER
    if:
      ${{ github.ref == 'refs/heads/feature/branch' }}
