name: learn github actions
on: [push]
env:
  SERVER: development
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "a code has been pushed"
      - run: echo "this step should only run on main branch"
    if:
      ${{ github.ref == 'refs/heads/master' }}
  build_and_test:
    runs-on: ubuntu-latest
    container: golang
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: testing...
        run : go test -v
        working-directory: ./greeting
  run_program:
    runs-on: ubuntu-latest
    container: golang
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: running the program...
        run: go run main.go
        working-directory: ./cmd
    needs: build_and_test
        


  hello-feature-branch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "pushing on feature branch"
      - run: echo "this step should only run on feature/branch"
      - run: echo $GITHUB_REF
      - run: echo $SERVER
    if:
      ${{ github.ref == 'refs/heads/feature/branch' }}
